- .github/workflows/ci.yml
- CONTRIBUTING.md
- README.md
- packages/ossa-demo/cypress.json
- packages/ossa-demo/package.json
> chore: add test result badge

- .changeset/strong-seahorses-suffer.md
- packages/ossa-demo/src/index.html
- packages/ossa/src/style/_mixin.scss
- packages/ossa/src/style/components/actionsheet.scss
优化ActionSheet组件的样式以更好地适配 iPhone X+ 机型
Fix issue #7 
> fix: style issue for ActionSheet

- .changeset/rude-snakes-end.md
- packages/ossa/src/style/components/badge.scss
> fix: Fixed a bug with word wrapping on the Badge component

- .changeset/happy-ways-wink.md
- packages/ossa-demo/src/components/layout/__test__/e2e.js
更新layout组件中的测试用例，以解决测试用例不通过的问题
> fix: Update the test cases for Layout

- .changeset/stale-coins-flow.md
- packages/ossa-demo/src/components/icon/demo/index.tsx
- packages/ossa-demo/src/components/tabbar/demo/index.tsx
- packages/ossa/src/components/tabbar/index.tsx
- packages/ossa/types/index.d.ts
- packages/ossa/types/tabbar.d.ts
> fix: OsTabBar类型定义

- scripts/checkModifyListAndTest.js
> fix: exit when test fail

- packages/ossa-demo/config/index.js
- packages/ossa-doc/docs/start.md
> Caedmon w patch 1

- .changeset/good-pianos-relate.md
- packages/ossa-demo/src/components/imagePreview/demo/index.tsx
- packages/ossa-demo/src/pages/index/index.tsx
- packages/ossa-doc/docs/组件/imagePreview.md
- packages/ossa/src/components/imagePreview/index.tsx
- packages/ossa/types/imagePreview.d.ts
- pnpm-lock.yaml
imagePreview组件优化：
- 预览时的header支持传入自定义样式
> imagePreview组件优化

- packages/ossa-demo/src/components/toast/__test__/e2e.js
> chore: cypress中文乱码

- packages/ossa-doc/docs/组件/animate.md
- packages/ossa/src/components/animate/index.tsx
- packages/ossa/types/animate.d.ts
> feat: 动画类型改为字面值联合类型,提升代码提示语开发体验

- .github/PULL_REQUEST_TEMPLATE.md
> chore: PR模版增加类型描述更新类型

- package.json
- packages/ossa/package.json
- pnpm-lock.yaml
因为想要开发查看效果，每次需要`pnpm build`后`pnpm dev:demo`查看，希望能够直接`pnpm dev`方便开发调试查看效果
> chore: 增加开发实时编译命令

- packages/ossa/src/components/toast/index.tsx
> fix: toast组件customStyle报错未生效

- .changeset/short-elephants-promise.md
- packages/ossa-demo/src/components/carousel/demo/index.tsx
- packages/ossa-doc/docs/组件/carousel.md
- packages/ossa/src/components/carousel/index.tsx
- packages/ossa/types/carousel.d.ts
> feat(Carousel): 走马灯点击回调支持传入当前点击子项索引

- .changeset/unlucky-baboons-beg.md
- packages/ossa-demo/src/components/carousel/demo/index.tsx
- packages/ossa-doc/docs/组件/carousel.md
- packages/ossa/src/components/carousel/index.tsx
- packages/ossa/src/style/components/carousel.scss
- https://github.com/NeteaseYanxuan/OSSA/issues/59
> fix(Carousel): 走马灯文档部分属性描述错误

- .changeset/young-jobs-relax.md
- packages/ossa-demo/src/components/badge/__test__/e2e.js
- packages/ossa-demo/src/components/badge/demo/index.tsx
- packages/ossa-doc/docs/组件/badge.md
- packages/ossa/src/components/badge/index.tsx
- fix: 修复 Badge 的 info 为 0 或为空时显示异常问题
- doc: 更新相关文档
- test cases: 更新相关测试用例
> fix(Badge): 修复 Badge 的 info 为 0 或为空时显示异常问题

- .changeset/light-humans-learn.md
- packages/ossa-demo/src/components/radio/demo/index.tsx
- packages/ossa-doc/docs/组件/radio.md
- packages/ossa/src/components/radio/index.tsx
- packages/ossa/src/components/radio/option/index.tsx
- packages/ossa/types/radio.d.ts
> feat: Radio 受控 可由 RadioGroup 控制

- .changeset/hot-lizards-prove.md
- packages/ossa-demo/src/components/input/demo/index.tsx
- packages/ossa-doc/docs/组件/input.md
- packages/ossa/types/input.d.ts
> docs: 删除冗余输入框类型

- .changeset/nervous-moons-eat.md
- packages/ossa-demo/src/components/input/demo/index.tsx
- packages/ossa-doc/docs/组件/input.md
- docs: 补充 showSplitLine 属性文档说明
> docs: 补充 showSplitLine 属性文档说明

- .changeset/lovely-turtles-dress.md
- packages/ossa-demo/src/components/navBar/demo/index.tsx
- packages/ossa-doc/docs/组件/navBar.md
docs: navBar 组件中 rightSlot 属性描述有误
> docs: navBar 组件中 rightSlot 属性描述有误

- .changeset/six-clouds-talk.md
- packages/ossa-demo/src/components/list/demo/index.tsx
- packages/ossa-doc/docs/组件/list.md
docs: 补充列表组件缺少的 `leftIconSize` 属性文档描述
> docs: 补充列表组件缺少的 leftIconSize 属性文档描述

- .changeset/smooth-feet-impress.md
- packages/ossa/src/components/actionsheet/index.tsx
- packages/ossa/src/components/actionsheet/item/index.tsx
- packages/ossa/src/components/animate/index.tsx
- packages/ossa/src/components/badge/index.tsx
- packages/ossa/src/components/button/index.tsx
- packages/ossa/src/components/carousel/index.tsx
- packages/ossa/src/components/col/index.tsx
- packages/ossa/src/components/common/pickerGroup/index.tsx
- packages/ossa/src/components/common/pickerPopup/index.tsx
- packages/ossa/src/components/datePicker/index.tsx
- packages/ossa/src/components/icon/index.tsx
- packages/ossa/src/components/imagePreview/index.tsx
- packages/ossa/src/components/input/index.tsx
- packages/ossa/src/components/list/index.tsx
- packages/ossa/src/components/navBar/index.tsx
- packages/ossa/src/components/picker/index.tsx
- packages/ossa/src/components/radio/index.tsx
- packages/ossa/src/components/radio/option/index.tsx
- packages/ossa/src/components/rate/index.tsx
- packages/ossa/src/components/row/index.tsx
- packages/ossa/src/components/search/index.tsx
- packages/ossa/src/components/stepper/index.tsx
- packages/ossa/src/components/tabbar/index.tsx
- packages/ossa/src/components/tabs/tabs-header-item/index.tsx
- packages/ossa/src/components/tag/index.tsx
- packages/ossa/src/components/toast/index.tsx
- packages/ossa/src/components/upload/index.tsx
> refactor: refactor call expression

- .changeset/grumpy-beans-thank.md
- packages/ossa-demo/src/components/tabbar/demo/index.tsx
- packages/ossa-doc/docs/组件/tabbar.md
- packages/ossa/src/components/tab-bar/index.tsx
- packages/ossa/types/tabbar.d.ts
> feat(tabBar): 完善 tab-bar 组件文档与类型描述

- .changeset/sour-pants-destroy.md
- packages/ossa-demo/src/components/stepper/demo/index.tsx
- packages/ossa-doc/docs/组件/stepper.md
- packages/ossa/types/stepper.d.ts
> feat(stepper): 补充步进器相关文档与类型描述

- .changeset/cold-tools-call.md
- packages/ossa-demo/src/components/rate/demo/index.tsx
- packages/ossa-doc/docs/组件/rate.md
- packages/ossa/src/components/rate/index.tsx
- packages/ossa/types/rate.d.ts
> feat(rate): 完善评分组件文档 & 优化属性命名

- packages/ossa/src/style/components/countdown.scss
> chore: 增加countdown.scss文件

- .changeset/little-lemons-explode.md
- packages/ossa-demo/src/app.config.ts
- packages/ossa-demo/src/components/swipeCell/__test__/e2e.js
- packages/ossa-demo/src/components/swipeCell/demo/index.config.ts
- packages/ossa-demo/src/components/swipeCell/demo/index.scss
- packages/ossa-demo/src/components/swipeCell/demo/index.tsx
- packages/ossa-demo/src/pages/feedback/index.tsx
- packages/ossa-doc/docs/组件/swipeCell.md
- packages/ossa/src/components/swipe-cell/index.tsx
- packages/ossa/src/index.ts
- packages/ossa/src/style/components/swipe-cell.scss
- packages/ossa/src/style/index.scss
- packages/ossa/types/index.d.ts
- packages/ossa/types/swipeCell.d.ts
> feat: 增加滑动单元格组件

- .changeset/forty-carrots-beg.md
- packages/ossa/src/components/input/index.tsx
> fix: fix input disabledClear

- .changeset/odd-rings-build.md
- packages/ossa-demo/src/components/stepper/demo/index.tsx
- packages/ossa-doc/docs/组件/stepper.md
- packages/ossa/src/components/stepper/index.tsx
- packages/ossa/types/stepper.d.ts
- fix: 修改部分 stepper 组件错误 与完善类型描述
> fix(stepper): 修改部分 stepper 组件错误 与完善类型描述

- .changeset/large-cameras-tell.md
- package.json
- packages/ossa-demo/src/components/upload/demo/index.tsx
- packages/ossa-doc/docs/组件/upload.md
- packages/ossa/package.json
- packages/ossa/src/components/upload/index.tsx
- packages/ossa/types/upload.d.ts
- pnpm-lock.yaml
`upload` 组件增加 `onImageClick` 方法
> Feature upload callback

- .changeset/sharp-phones-do.md
- packages/ossa-demo/src/components/upload/__test__/e2e.js
- packages/ossa-demo/src/components/upload/demo/index.tsx
- packages/ossa-doc/docs/组件/upload.md
- packages/ossa/src/components/upload/index.tsx
- packages/ossa/types/upload.d.ts
- fix: 修复 upload 组件 max 和 multiple 属性不生效问题
**关联ISSUE**
- #108 
> fix: 修复 upload 组件 max 和 multiple 属性不生效问题

- packages/ossa-demo/src/components/swipeCell/__test__/e2e.js
`swiperCell` 测试用例在CI中执行结果不稳定，有时会失败
> fix: test case result not stable in CI

- .changeset/tame-wombats-yell.md
- packages/ossa/src/components/modal/index.tsx
- packages/ossa/src/style/components/modal.scss
- packages/ossa/types/modal.d.ts
> fix(Modal): 弹窗圆角

- .changeset/gold-planets-sing.md
- packages/ossa-demo/src/components/modal/demo/index.tsx
- packages/ossa-doc/docs/组件/modal.md
- packages/ossa/src/components/input/index.tsx
- packages/ossa/src/components/modal/index.tsx
- packages/ossa/src/components/rate/index.tsx
- packages/ossa/src/components/stepper/index.tsx
- packages/ossa/src/components/tab-bar/index.tsx
- packages/ossa/src/utils/index.ts
- packages/ossa/types/modal.d.ts
- fix: 修复因默认值导致过期属性合并异常问题 #123 
> fix: 修复因默认值导致过期属性合并异常问题

- .changeset/silly-houses-hug.md
- packages/ossa-demo/src/app.ts
- packages/ossa/src/style/components/date-picker.scss
- packages/ossa/src/style/components/picker.scss
修复动态引入时，`picker` 和 `datePciker` 组件样式文件缺失
> fix: css file lost when dynamic import

- .changeset/wise-rocks-arrive.md
- packages/ossa-demo/src/components/tabs/__test__/e2e.js
- packages/ossa-demo/src/components/tabs/demo/index.tsx
- packages/ossa/src/components/tabs-header-item/index.tsx
- packages/ossa/src/style/components/tabs-header-item.scss
> fix(Tab): tab not ellipsis

- .github/workflows/ci.yml
- .github/workflows/cypress.yml
- packages/ossa-demo/src/components/icon/__test__/e2e.js
- packages/ossa-demo/src/components/list/__test__/e2e.js
- packages/ossa-demo/src/components/picker/__test__/e2e.js
> chore: support Chinese when run test

- .changeset/stale-rings-exercise.md
- .github/workflows/preview.yml
- packages/ossa-demo/src/components/input/demo/index.tsx
- packages/ossa-doc/docs/组件/input.md
- packages/ossa/types/input.d.ts
> Feature input props

- .changeset/gorgeous-melons-dress.md
- packages/ossa/src/components/common/pickerGroup/index.tsx
- packages/ossa/src/components/input/index.tsx
- packages/ossa/types/input.d.ts
> fix: picker style error in weapp

- .changeset/strong-ads-greet.md
- .gitignore
- packages/ossa-demo/src/components/search/__test__/e2e.js
- packages/ossa-demo/src/components/search/demo/index.tsx
- packages/ossa-doc/docs/组件/search.md
- packages/ossa/src/components/search/index.tsx
- packages/ossa/types/search.d.ts
> Feature search
